[pytest]
# Enable verbose logging (-v) and generate a self-contained HTML report
addopts = -v --html=report.html --self-contained-html

# Specify the directory where pytest should look for test files
testpaths = tests

# Add root directory to PYTHONPATH to resolve custom modules (e.g., 'pages', 'base')
pythonpath = .